/Users/u1123114/Documents/projects/kinbank/kinura/env/lib/python3.10/site-packages/clldutils/clilib.py:257: UserWarning: cannot import name 'SNIMissingWarning' from 'urllib3.exceptions' (/Users/u1123114/Documents/projects/kinbank/kinura/env/lib/python3.10/site-packages/urllib3/exceptions.py) cldfbench.commands.media
  warnings.warn('{0} {1}'.format(e, modname))
[32mINFO   [0m running _cmd_makecldf on kinbank ...[0m
[32mINFO   [0m file written: /Users/u1123114/Documents/projects/kinbank/kinura/kinbank/cldf/.transcription-report.json[0m
[32mINFO   [0m Summary for dataset /Users/u1123114/Documents/projects/kinbank/kinura/kinbank/cldf/cldf-metadata.json
- **Varieties:** 19
- **Concepts:** 226
- **Lexemes:** 3,132
- **Sources:** 38
- **Synonymy:** 1.37[0m
[32mINFO   [0m file written: /Users/u1123114/Documents/projects/kinbank/kinura/kinbank/TRANSCRIPTION.md[0m
[32mINFO   [0m file written: /Users/u1123114/Documents/projects/kinbank/kinura/kinbank/cldf/lingpy-rcParams.json[0m
[32mINFO   [0m ... done kinbank [141.5 secs][0m
